version: "3.8"
name: "streamer_test"

# XIU test pod
services:

  # 1. Build
  app:
    build:
      context: "."
      target: "runner"

    # Or use image
    # image: "normkd/1688557675-test01:1.0.0"

  # 2. Base streamer
  base_streamer:
    extends:
      service: "app"

    # Container config
    container_name: "${COMPOSE_PROJECT_NAME}.node0"
    
    # App config
    working_dir: "/app"
    user: "appuser"

    # Base network
    hostname: "base_streamer"
    networks:
      local:
        ipv4_address: "172.16.100.5"
    
    ports:
      - "1935:1935"
      - "1935:1935/udp"
      - "8000:8000" 
      - "8000:8000/udp"

    # If using "*.docker.internal subdomain"
    extra_hosts:
      - "host.docker.internal:host-gateway"

    # Run
    entrypoint: ["xiu"]
    command: ["-c", "config/config_rtmp.toml"]


  # 3. Streamer instances
  streamer1:

    # Extending app service
    extends:
      service: "base_streamer"

    # Override/extend container config
    container_name: "${COMPOSE_PROJECT_NAME}.node1"

    # Network
    hostname: "streamer1"
    networks:
      local:
        ipv4_address: "172.16.100.6"

  streamer2:

    # Extending app service
    extends:
      service: "base_streamer"

    # Override/extend container config
    container_name: "${COMPOSE_PROJECT_NAME}.node2"

    # Network
    hostname: "streamer2"
    networks:
      local:
        ipv4_address: "172.16.100.7"

# ---

configs:
  xiu_config:
    file: "./config/config_rtmp.toml"
    name: "default"
    # external: true

# ---

networks:
  local:
    name: "intra"
    ipam:
      config:
        - subnet: "172.16.100.0/24"
    # driver: "bridge"
