version: '3.8'

# XIU test cluster
services:
  xiu1:
    image: "normkd/1688557675-0f6cc0425e5dfba9fd0951bba6251d62:1.0.0"
    hostname: "xiu1"
    networks:
      intranet:
        ipv4_address: 192.168.0.1
        
    ports:
      - 1935:1935
      - 1936:1936
      - 8080:8080
      - 8081:8081
    extra_hosts:
      - "host.docker.internal:host-gateway"

  # xiu2:
  #   image: "normkd/1688557675-0f6cc0425e5dfba9fd0951bba6251d62:1.0.0"
  #   hostname: "xiu1"
  #   networks:
  #     internal:
  #       ipv4_address: 192.168.0.2
  #   ports:
  #     - 1935:1935
  #     - 1936:1936
  #     - 8080:8080
  #     - 8081:8081
  #   # extra_hosts:
  #   #   - "host.docker.internal:host-gateway"

  # xiu3:
  #   image: "normkd/1688557675-0f6cc0425e5dfba9fd0951bba6251d62:1.0.0"
  #   hostname: "xiu1"
  #   networks:
  #     internal:
  #       ipv4_address: 192.168.0.3
  #   ports:
  #     - 1935:1935
  #     - 1936:1936
  #     - 8080:8080
  #     - 8081:8081
  #   # extra_hosts:
  #   #   - "host.docker.internal:host-gateway"

networks:
  intranet:
    name: testnet
    ipam:
      driver: default
      config:
        - subnet: 192.168.0.0/24
  nonet:
    name: none
    external: true
