version: "3.8"
name: "xiu-streamer-test"

# XIU test pod
services:
  stream:
    # image: "normkd/1688557675-0f6cc0425e5dfba9fd0951bba6251d62:1.0.0"
    build: "."
    hostname: "restreamer"
    networks:
      - "intranet"
    ports:
      - "80:80/tcp"
      - "80:80/udp"
      - "443:443"
      - "1935:1935"
      - "1936:1936"
      - "8080:8080"
      - "8081:8081"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    deploy:
      replicas: 3
      mode: "dnsrr"
      endpoint_mode: "dnsrr"
      labels:
        nodes.replicated: "Replicated solve." 

networks:
  intranet:
    name: "local"
    driver: "bridge"
