version: "3.8"
# name: "xiu-streamer-test"

# XIU test pod
services:
  stream:
    build: "."
    image: "normkd/1688557675-86299174e27a0c2237b2211c55c3e188:1.0.0"
    container_name: "${COMPOSE_PROJECT_NAME}.node"
    hostname: "restreamer"
    networks:
      - "intranet"
    ports:
      - "80:80/tcp"
      - "80:80/udp"
      - "443:443"
      - "1935:1935"
      - "1936:1936"
      - "8080:8080"
      - "8081:8081"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    deploy:
      replicas: 3
      mode: "dnsrr"
      endpoint_mode: "dnsrr"
      labels:
        nodes.replicated: "Replicated solve."

networks:
  intranet:
    name: "local"
    driver: "bridge"
