version: "3.8"
# name: "xiu-streamer-test"

# XIU test pod
services:
  stream1:
    build:
      context: "."
      target: "runner"
    image: "normkd/1688557675-11da8b5844776744b42ffae53506bca8:1.0.0"
    container_name: "${COMPOSE_PROJECT_NAME}.node0"
    hostname: "streamer1"
    networks:
      - "local"
    ports:
      - "80:80"
      - "80:80/udp"
      - "443:443"
      - "1935:1935"
      - "1935:1935/udp"
      - "1936:1936"
      - "1936:1936/udp"
      - "8000:8000"
      - "8000:8000/udp"
      - "8080:8080"
      - "8080:8080/udp"
      - "8081:8081"
      - "8001:8001/udp"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    configs:
      - "xiu_config"
  
  stream2:
    build:
      context: "."
      target: "runner"
    image: "normkd/1688557675-11da8b5844776744b42ffae53506bca8:1.0.0"
    container_name: "${COMPOSE_PROJECT_NAME}.node1"
    hostname: "streamer2"
    networks:
      - "local"
    ports:
      - "80:80"
      - "80:80/udp"
      - "443:443"
      - "1935:1935"
      - "1935:1935/udp"
      - "1936:1936"
      - "1936:1936/udp"
      - "8000:8000"
      - "8000:8000/udp"
      - "8080:8080"
      - "8080:8080/udp"
      - "8081:8081"
      - "8001:8001/udp"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    configs:
      - "xiu_config"

  stream3:
    build:
      context: "."
      target: "runner"
    container_name: "${COMPOSE_PROJECT_NAME}.node2"
    image: "normkd/1688557675-11da8b5844776744b42ffae53506bca8:1.0.0"
    configs:
      - "xiu_config"
    hostname: "streamer3"
    networks:
      - "local"
    ports:
      - "80:80"
      - "80:80/udp"
      - "443:443"
      - "1935:1935"
      - "1935:1935/udp"
      - "1936:1936"
      - "1936:1936/udp"
      - "8000:8000"
      - "8000:8000/udp"
      - "8080:8080"
      - "8080:8080/udp"
      - "8081:8081"
      - "8001:8001/udp"
    extra_hosts:
      - "host.docker.internal:host-gateway"

configs:
  xiu_config:
    file: "config/config_rtmp.toml"
    name: "rtmp_conf"

networks:
  local:
    name: "lan"
    driver: "bridge"
