version: "3"
name: "streamer_test"

# XIU test pod
services:

  # 1. Base streamer
  base_streamer:
    build:
      context: "."
      target: "test_runner"
    image: "normkd/1688557675-test01:1.0.0"
    container_name: "${COMPOSE_PROJECT_NAME}.node0"
    working_dir: "/app"
    volumes:
      - "./config:/app/config"
    user: "appuser"
    hostname: "base_streamer"
    networks:
      - "intra"
      # intra:
        # ipv4_address: "172.16.100.5"
    ports:
      - "1935"
      # - "1935:1935/udp"
      # - "8000:8000" 
      # - "8000:8000/udp"
    # extra_hosts:
    #   - "host.docker.internal:host-gateway"
    command: ["-c", "config/config_rtmp.toml"]

  # 2. Streamer instances
  streamer1:
    extends:
      service: "base_streamer"
    container_name: "${COMPOSE_PROJECT_NAME}.node1"
    hostname: "streamer1"
    # ports:
    #   - "1936:1936"
    # networks:
      # intra:
        # ipv4_address: "172.16.100.6"

  streamer2:
    extends:
      service: "base_streamer"
    container_name: "${COMPOSE_PROJECT_NAME}.node2"
    hostname: "streamer2"
    # ports:
    #   - "1937:1937"
    # networks:
    #   intra:
    #     ipv4_address: "172.16.100.7"

networks:
  intra:
    name: "test_bridge"
    driver: "ipvlan"
    ipam:
      config:
        - subnet: "172.100.0.0/24"
  # default:
  #   external: true
  #   name: "nat"
