version: "3"
name: "streamer_test"

# XIU test pod
services:

  # 1. Base streamer
  base_streamer:
    build:
      context: "."
      target: "test_runner"
    image: "normkd/1688557675-test01:1.0.0"
    container_name: "${COMPOSE_PROJECT_NAME}.node0"
    environment:
      - TZ="Europe/Moscow"
    working_dir: "/app"
    volumes:
      - "./config:/app/config"
    user: "appuser"
    hostname: "base-streamer"
    # networks:
    #   intra:
    #     ipv4_address: "172.16.100.5"
    # ports:
    #   - "55001:1935"
    #   - "1935:1935/udp"
    #   - "8000:8000" 
    #   - "8000:8000/udp"
    # extra_hosts:
    #   - "host.docker.internal:host-gateway"
    command: ["-c", "config/config_rtmp.toml"]

  # 2. Streamer instances
  streamer1:
    extends:
      service: "base_streamer"
    container_name: "${COMPOSE_PROJECT_NAME}.node1"
    hostname: "streamer1"
    # ports:
    #   - "55002:1935"
    #   - "8000:8000"
    # networks:
    #   intra:
    #     ipv4_address: "172.16.110.6"

  streamer2:
    extends:
      service: "base_streamer"
    container_name: "${COMPOSE_PROJECT_NAME}.node2"
    hostname: "streamer2"
    # ports:
    #   - "55003:1935"
    #   - "8000:8000"
    # networks:
    #   intra:
    #     ipv4_address: "172.16.120.5"

networks:
  intra:
    external: false
    attachable: false
    enable_ipv6: false
    name: "testnet"
    driver: "ipvlan"
    driver_opts:
      ipvlan_mode: "l2"
      ipvlan_flag: "bridge"

    # ipam:
    #   config:
    #     - subnet: "172.16.100.0/24"
        # - ip_range: "172.16.100.0/28"
        # - gateway: "172.16.100.10"
